# Generated by Django 5.2.14 on 2026-08-11 23:23

from django.db import migrations


def detach_legacy_profile_table(apps, schema_editor):
    """Preserve data left by the removed profiles app before Author is deleted."""
    table_names = schema_editor.connection.introspection.table_names()
    if "profiles_profile" not in table_names:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, name, about, author_id FROM profiles_profile")
        profile_rows = cursor.fetchall()

    schema_editor.execute('ALTER TABLE "profiles_profile" RENAME TO "profiles_profile_legacy"')
    schema_editor.execute(
        'CREATE TABLE "profiles_profile" ('
        '"id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, '
        '"name" varchar(50) NOT NULL, '
        '"about" text NOT NULL, '
        '"author_id" bigint NOT NULL UNIQUE)'
    )

    if profile_rows:
        with schema_editor.connection.cursor() as cursor:
            cursor.executemany(
                "INSERT INTO profiles_profile (id, name, about, author_id) "
                "VALUES (%s, %s, %s, %s)",
                profile_rows,
            )

    schema_editor.execute('DROP TABLE "profiles_profile_legacy"')


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0002_alter_posts_author'),
    ]

    operations = [
        migrations.RunPython(
            detach_legacy_profile_table,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
