# Generated by Django 5.2.14 on 2026-08-11 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_author_posts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='User',
            new_name='author',
        ),
    ]
